name: Create Issue

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue
        uses: github-script
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.repository }}
          ISSUE_TITLE: ${{ github.event.client_payload.title }}
          ISSUE_BODY: ${{ github.event.client_payload.body }}
        script: |
          curl -X POST \
            https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues \
            -H 'Authorization: Bearer ${TOKEN}' \
            -H 'Content-Type: application/json' \
            -d '{"title":"${ISSUE_TITLE}","body":"${ISSUE_BODY}"}'
