name: Submit Issue

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the submitter'
        required: true
      title:
        description: 'Title of the issue'
        required: true
      body:
        description: 'Body of the issue'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const { name, title, body } = github.context.payload.inputs;
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: `**Submitted by:** ${name}\n\n${body}`
            });
            await github.rest.projects.createCard({
              column_id: 'f971fb55',
              content_id: issue.data.id,
              content_type: 'Issue'
            });
        env:
          # GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GITHUB_TOKEN: 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
