name: Submit Issue

on:
  repository_dispatch:
    types: [submit-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const { name, title, body } = github.context.payload.client_payload;
            const octokit = github.getOctokit(github.context.repo.token);
            const issue = await octokit.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: `**Submitted by:** ${name}\n\n**Last Updated Time:** ${github.context.payload.client_payload.time}\n\n${body}`
            });
            await octokit.projects.createCard({
              column_id: 'f971fb55',
              content_id: issue.data.id,
              content_type: 'Issue'
            });
