name: Submit Issue

on:
  repository_dispatch:
    types: [submit-issue]

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        uses: actions/github-script@v4
        with:
          script: |
            const { name, title, body } = github.context.payload.client_payload;
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: `**Submitted by:** ${name}\n\n${body}`
            });
            await github.rest.projects.createCard({
              column_id: 'f971fb55',
              content_id: issue.data.id,
              content_type: 'Issue'
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
